### ISSUE TITLE
Not able to run the project in Debug mode(x64)

### ISSUE THREAD

**Issue by vivekatoffice** [lot3worx/AxisDemoSample#1]
Hi @lot3worx ,
Tried cloning the project and started the project. 

![image](https://github.com/lot3worx/AxisDemoSample/assets/52032125/fef50ace-8b3b-4b4a-a957-6834ad84fad3)

Do I need to install something on system?

**Comment by vivekatoffice** [comment]
Able to get the UI working.

![image](https://github.com/lot3worx/AxisDemoSample/assets/52032125/bf4b2544-f86f-4721-9e63-1f1b98ca0fb6)

**Comment by lot3worx** [comment]
Dear Vivek,

 

You got the UI working OK which is good. We stripped an app template down to “bare bones” to reproduce the error.. All you should need to do is to either hard code an Axis Onvif device credentials as the test target into the relevant variables, or fill them out in the credentials dialog. The app should then try to open a device management channel and retrieve all the Xaddr service addresses and in particular the event service xaddr to open the correct event control channel, then do  Geteventproperties request (which should be successful), after which it should try to get the GetServiceCapabilitesRequest and throw the fault we have been discussing.

 

Remember that the Xaddr you have to fill out is the Onvif device service Xaddr string but you probably already know that given you work with Axis devices. The placeholder text in the credential dialog box is an example of the Axis style implementation with …/onvif/device_service as the path after the IP address.

**Comment by vivekatoffice** [comment]
Hi @lot3worx ,
Able to get the Error on my system now:
![image](https://github.com/lot3worx/AxisDemoSample/assets/52032125/d65e736e-de36-4ed7-a860-5724670b9bd6)

I will try to play with it and find someone with more experience with it. Thank you for your efforts to report this.

**Comment by vivekatoffice** [comment]
Hi @lot3worx ,
Hope you have checked this: https://stackoverflow.com/questions/56423255/wcf-request-returns-wrong-response

Any thoughts?
